version: '2.1'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  service_agent:
    build: ./sdk
    image: jolocom/sdk
    restart: unless-stopped
    volumes:
      - ./service_agent:/app
    ports:
      - "9000:9000"
    environment:
      JWT_COMMAND: 'docker-compose run rpc_agent start'
      PUBLIC_HOSTPORT: 'service_agent:9000'
      DEBUG: 1

  rpc_agent:
    build: ./sdk
    image: jolocom/sdk
    volumes:
      - ./rpc_agent:/app
